### ISSUE TITLE
Placing Dhamma-Vinaya improper

### ISSUE THREAD

**Issue by ghost** [sasanarakkha/study-tools#15]
Venerables,

it's total improper, not increasing faith and damaging a lot, that the Venerables do not only put the Sublime Dhamma-Vinaya, Ariya-Dhamma, under common creative, take lay-people owned and change borders, place it by not given means, and actually as the root course, without any reference and devotion on market places.

Having just shortly taken on an account here, to try to prevents from huge damage by the SC-robbers, it's sad but truth to seen another fallen apart. [ការលួចចម្លងព្រះត្រៃបិដកខ្មែ Undertaking to copy-steal Khmer Tipitaka by SC-monks](https://forum.sangham.net/index.php?topic=10578.msg27628#msg27628)

Sincerely wishing yours to find hopefully a timely escape. Since not a year more, if not already, and no more Bhikkhu anywhere to find.

**Comment by Devamitta** [comment]
Thanks for your feedback.

Can you be more specific? Which things you are talking about, and what do you suggest? Your constructive feedback can help us to improve.

**Comment by ghost** [comment]
> Re: [sasanarakkha/study-tools] Placing Dhamma-Vinaya improper (Issue #15) 
> – Thanks for your feedback.
>
> Can you be more specific? Which things you are talking about, and what 
> do you suggest? Your constructive feedback can help us to improve.

Venerable friend of the Devas, or friend, deva-like, Bhante,

Sadhu, at least for showing interest, Sadhu for giving leave.

* It's improper, till even heavy transgression to make use of others, not 
really given, means. Improper to make use of traded "free" and sign even 
contracts.
* It's improper, and depriving the Sangha of it's heritage to put what ever 
Dhamma Vinaya under common, public, creative domain, allowing consciously 
doing harmful and against the Dhamma as well.
* It's improper to teach Dhamma-Vinaya to householders, first when they 
had not shown signs of respect (of which a take-away hardly leads even to 
thanks after taken). Even toward Bhikkhus are there, especially in regard 
of Vinaya, clear rules.
* It's improper to teach Dhamma-Vinaya in ways, that it could be gained 
equal the Bhikkhus, since non-Bhikkhus would lose respect, make the Bhikkhu 
Sangha just a burdensome institution.
* It's improper to make use of householder controlled Dhamma, without being 
given.
* It's improper to store the Dhamma without even Namo... above, like another 
hobby-cellar of a social-rent apartment house.
*It's not at all inspiring to approach Dhamma-Vinaya like tasks task marxist 
kibutz.

Aside of the surely much required cleaning, which will not be easy, as hardly 
one to find without wrongs of many kind, here short a reminder on a given 
and open future way, at least as sample, if other things might be obstacles 
(which can be all of course cleared, if showing signs).

Long, long time sawn the dangers soon destroying the Sasana by all-fallen 
down Bhikkhus, my person spended a lot of time to do not only try to provide 
clean and given space, but also could obtain a lot, yet last, Dhamma for 
the Sangha, all at least on one side purified.

My person had already given once, invited, and Bhante Ariyadhammika even 
has Admin-possibilities, yet told that he and his fellows have no lack and 
need yet, to make use of sangham.net (doku-wiki) and all the given.

My person is aware of the total crazy and wrong-view feeded interpretations 
on IT and modern means regards (of, at least, those having engaged in ways, 
that they need those interpretation to walk on...), but they are simply 
wrong, have cause many already fall apart and block a huge number form progressing. 
Not taken what isn't given, or with bonds back, is very very simple, as 
giving and respect first, before sharing the Dhamma, is like-a-like clear 
and simple, yet defilements and desires of gains may seek all ways around.

Bhante is given, like his fellows as well, to make use of delta-chat (email-chat, 
good for voice, attachments, easy to use, save as well, for those no faith 
in kamma yet). If lacking access, accounts, email... what ever avaliable, 
my person is glad to put on effort to share it further. May the Venerables 
accept all and make proper use of it.

May Bhante, if not right in the moment get very clear of all, not seek for 
going around, and solve the many issues with his fellows very clear and 
strict. My person would share what ever encouragement or proper understanding, 
right next to the means offered.

My person is not sure where this email via a github-mail list goes to, and 
does not like to further use it. My persons email, if lacking given access, 
is samana.johann@sangham.net

-- 
metta and Mudita
May one always feel welcome at sangham.net
(using Sangha messenger, info and download: https://forum.sangham.net/index.php?action=tpmod;dl=item757 )

**Comment by ghost** [comment]
Since improper to make use of all this here, may the Venerables make use 
of the topic in "Monastic intern social area": github, copy, and other issues, 
Sasanarakkha https://forum.sangham.net/index.php?topic=10946.msg30588#msg30588

-- 
metta and Mudita
May one always feel welcome at sangham.net
(using Sangha messenger, info and download: https://forum.sangham.net/index.php?action=tpmod;dl=item757 )

**Comment by Devamitta** [comment]
Thank you for sharing. We will see how this info can help us to improve.
