### ISSUE TITLE
What is DHP?

### ISSUE THREAD

**Issue by thesunshade** [sasanarakkha/study-tools#16]
I'm looking at this page: https://sasanarakkha.github.io/study-tools/anki-decks/dhp-vocab.html

And I can't figure out what DHP is. It's a good policy to always define acronyms. It's easy to forget that not everyone that can benefit from resources is part of the in-crowd. Acronyms should always be spelled out in their first use in a document.

Thanks for making all these resources available to the public!

Much merit!

**Comment by Devamitta** [comment]
Thank you for bringing this to my attention. I have made the necessary corrections.

**Comment by thesunshade** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️

Omg. Now it's obvious. I guess I was just thinking the D must mean dictionary and the P must mean Pali. Usually I see Dhammapada abbreviated as Dhp, not DHP.

Any way, thanks for all your work!
